services:
    # Web API (Dockerfile runtime)
    - type: web
      name: ctcare-api
      runtime: docker
      plan: free
      dockerfilePath: Dockerfile
      autoDeploy: false # let CI trigger via Deploy Hook
      healthCheckPath: /health

      envVars:
          # Bind Kestrel to Render's provided port
          - key: ASPNETCORE_URLS
            value: http://0.0.0.0:${PORT}

          # Environment
          - key: DOTNET_ENVIRONMENT
            value: Production
          - key: ASPNETCORE_ENVIRONMENT
            value: Production

          # Database (DefaultConnection)
          - key: ConnectionStrings__DefaultConnection
            fromDatabase:
                name: ctcare-db
                property: connectionString

          # Redis (ConnectionString + tuning copied from appsettings)
          - key: RedisSetting__ConnectionString
            fromService:
                name: ctcare-redis
                type: redis
                property: connectionString
          - key: RedisSetting__ConnectionString
            value: red-<id>:6379
          - key: RedisSetting__Password
            value: <internal-auth-token>
          - key: RedisSetting__SlidingExpiration
            value: "12:00:00"
          - key: RedisSetting__AbsoluteExpiration
            value: "24:00:00"
          - key: RedisSetting__SyncTimeOut
            value: "1000"
          - key: RedisSetting__ConnectTimeout
            value: "5000"
          - key: RedisSetting__ConnectRetry
            value: "5"
          - key: RedisSetting__AbortOnConnectFail
            value: "false"

          - key: Sentry__Dsn
            sync: false
          - key: SentryKey
            sync: false

          - key: Auth__ApiKeys__0
            sync: false

          - key: RateLimiting__RequestsPerMinute
            value: "60"
          - key: RateLimiting__Burst
            value: "20"

    # --- Redis cache (managed) ---
    - type: redis
      name: ctcare-redis
      plan: free
      ipAllowList: [] # internal only

databases:
    - name: ctcare-db
      plan: free
      ipAllowList: [] # internal only
